<div style="font-size: 12px;">
<span class="info_attention"><u><b>Внимание!!!</b></u>&nbsp;Данный магазин является партнером My-shop.ru.</span><br><br>Телефоны My-shop.ru:<ul><li>(495) 638-53-38 - для Москвы,</li><li>8 (800) 100-53-38 - бесплатно для РФ.</li></ul>
Телефоны многоканальные: понедельник-пятница - 9:00-21:00, суббота-воскресенье - 10:00-19:00.<br><br>
Более полная информация доступна на <a href="http://my-shop.ru/?partner=<?= $this->partner_id ?>">My-shop.ru</a>
</div>