<script type="text/javascript">
var myShopPartnerId = '<?= $this->layout()->partner_id ?>';
var myShopExternalCSS = '<?= DOMAIN_PATH ?>/css/shop_style.css';
document.write('<div><iframe id="myShopOnelineCartIframe" src="http://p.my-shop.ru/order?action=embedCart&partner='+myShopPartnerId+'&'+location.search.substring(1)+(myShopExternalCSS?'&extcss='+encodeURIComponent(myShopExternalCSS):'')+'&nocache='+Math.ceil(Math.random()*1000000)+'" height="20" width="200" style="margin: 0; padding: 0; border: 0;" scrolling="no" frameborder="0"></iframe></div>');
</script>
<div style="position: absolute;left:975px;top:120px;">
<a href="<?= DOMAIN_PATH.'/shop/basket' ?>"><img src="<?= DOMAIN_PATH ?>/images/basket.png" title="Корзина" style="border:0px;"></a>
</div>