<div class="footer">
	<div class="footer_copyright">
		&copy; 2011-<?= date('Y') ?> <a href="<?php echo $this->serverUrl(); ?>">Интернет-магазин детских игрушек igrushki-detkam.ru</a><br/>
	</div>
	<div class="meter">
		<?php echo $this->partial('liveinternet_stat.phtml'); ?>
		<?php echo $this->partial('mail_stat.phtml'); ?>
		<?php echo $this->partial('rambler_stat.phtml'); ?>
	</div>
	<div class="many_toys"></div>
</div>